name: bfluids-env
channels:
  - conda-forge
  - defaults
dependencies:
  - python
  - pip
  - black
  - rich
  - coolprop
  - numpy==1.26.4
  - scipy==1.11.4
  - pandas==2.1.4
  - scikit-learn==1.4.2
  - pycaret==3.3.2
  - matplotlib==3.7.3
  - matplotlib-label-lines==0.7.0
  - scienceplots==2.1.1
